#############################################################################
# Makefile for building: QtNewProject
# Generated by qmake (3.1) (Qt 5.12.0)
# Project:  QtNewProject.pro
# Template: subdirs
# Command: D:\Soft\Qt5.12.0\5.12.0\msvc2017_64\bin\qmake.exe -o Makefile QtNewProject.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = D:\Soft\Qt5.12.0\5.12.0\msvc2017_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Soft\Qt5.12.0\5.12.0\msvc2017_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Soft\Qt5.12.0\5.12.0\msvc2017_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-Books \
		sub-Draws \
		sub-MainWidget


sub-Books-qmake_all:  FORCE
	@if not exist Books\ mkdir Books\ & if not exist Books\ exit 1
	cd Books\ && $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Books\Books.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Books\ && $(MAKE) -f Makefile qmake_all
sub-Books: FORCE
	@if not exist Books\ mkdir Books\ & if not exist Books\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Books\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Books\Books.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Books-make_first: FORCE
	@if not exist Books\ mkdir Books\ & if not exist Books\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Books\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Books\Books.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Books-all: FORCE
	@if not exist Books\ mkdir Books\ & if not exist Books\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Books\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Books\Books.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Books-clean: FORCE
	@if not exist Books\ mkdir Books\ & if not exist Books\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Books\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Books\Books.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Books-distclean: FORCE
	@if not exist Books\ mkdir Books\ & if not exist Books\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Books\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Books\Books.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Books-install_subtargets: FORCE
	@if not exist Books\ mkdir Books\ & if not exist Books\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Books\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Books\Books.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Books-uninstall_subtargets: FORCE
	@if not exist Books\ mkdir Books\ & if not exist Books\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Books\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Books\Books.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Draws-qmake_all:  FORCE
	@if not exist Draws\ mkdir Draws\ & if not exist Draws\ exit 1
	cd Draws\ && $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Draws\Draws.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Draws\ && $(MAKE) -f Makefile qmake_all
sub-Draws: FORCE
	@if not exist Draws\ mkdir Draws\ & if not exist Draws\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Draws\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Draws\Draws.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Draws-make_first: FORCE
	@if not exist Draws\ mkdir Draws\ & if not exist Draws\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Draws\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Draws\Draws.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Draws-all: FORCE
	@if not exist Draws\ mkdir Draws\ & if not exist Draws\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Draws\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Draws\Draws.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Draws-clean: FORCE
	@if not exist Draws\ mkdir Draws\ & if not exist Draws\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Draws\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Draws\Draws.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Draws-distclean: FORCE
	@if not exist Draws\ mkdir Draws\ & if not exist Draws\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Draws\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Draws\Draws.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Draws-install_subtargets: FORCE
	@if not exist Draws\ mkdir Draws\ & if not exist Draws\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Draws\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Draws\Draws.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Draws-uninstall_subtargets: FORCE
	@if not exist Draws\ mkdir Draws\ & if not exist Draws\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Draws\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Draws\Draws.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MainWidget-qmake_all:  FORCE
	@if not exist MainWidget\ mkdir MainWidget\ & if not exist MainWidget\ exit 1
	cd MainWidget\ && $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\MainWidget\MainWidget.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MainWidget\ && $(MAKE) -f Makefile qmake_all
sub-MainWidget: FORCE
	@if not exist MainWidget\ mkdir MainWidget\ & if not exist MainWidget\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MainWidget\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\MainWidget\MainWidget.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MainWidget-make_first: FORCE
	@if not exist MainWidget\ mkdir MainWidget\ & if not exist MainWidget\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MainWidget\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\MainWidget\MainWidget.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MainWidget-all: FORCE
	@if not exist MainWidget\ mkdir MainWidget\ & if not exist MainWidget\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MainWidget\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\MainWidget\MainWidget.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MainWidget-clean: FORCE
	@if not exist MainWidget\ mkdir MainWidget\ & if not exist MainWidget\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MainWidget\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\MainWidget\MainWidget.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MainWidget-distclean: FORCE
	@if not exist MainWidget\ mkdir MainWidget\ & if not exist MainWidget\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MainWidget\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\MainWidget\MainWidget.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MainWidget-install_subtargets: FORCE
	@if not exist MainWidget\ mkdir MainWidget\ & if not exist MainWidget\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MainWidget\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\MainWidget\MainWidget.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MainWidget-uninstall_subtargets: FORCE
	@if not exist MainWidget\ mkdir MainWidget\ & if not exist MainWidget\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MainWidget\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\MainWidget\MainWidget.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: QtNewProject.pro ..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\win32-msvc\qmake.conf ..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\spec_pre.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\common\angle.conf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\common\windows-vulkan.conf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\common\msvc-desktop.conf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\qconfig.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_charts.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_core.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_designer.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_gui.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_help.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_location.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_network.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_networkauth.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_purchasing.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_purchasing_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qml.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quick.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_script.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_script_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_sql.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_svg.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webengine.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webengine_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webenginecore.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webview.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_xml.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\qt_functions.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\qt_config.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\win32-msvc\qmake.conf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\exclusive_builds.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\common\msvc-version.conf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\toolchain.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\default_pre.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\win32\default_pre.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\resolve_config.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\exclusive_builds_post.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\default_post.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\qml_debug.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\precompile_header.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\warn_on.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\qmake_use.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\file_copies.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\win32\windows.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\testcase_targets.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\exceptions.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\yacc.prf \
		..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\lex.prf \
		QtNewProject.pro
	$(QMAKE) -o Makefile QtNewProject.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\spec_pre.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\common\angle.conf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\common\windows-vulkan.conf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\common\msvc-desktop.conf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\qconfig.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_charts.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_charts_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_core.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_designer.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_gui.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_help.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_location.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_network.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_networkauth.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_networkauth_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_purchasing.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_purchasing_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qml.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quick.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_script.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_script_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_scripttools.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_sql.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_svg.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_virtualkeyboard.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webengine.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webengine_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webenginecore.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webview.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_xml.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\qt_functions.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\qt_config.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\win32-msvc\qmake.conf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\spec_post.prf:
.qmake.stash:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\exclusive_builds.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\common\msvc-version.conf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\toolchain.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\default_pre.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\win32\default_pre.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\resolve_config.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\exclusive_builds_post.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\default_post.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\qml_debug.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\precompile_header.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\warn_on.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\qmake_use.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\file_copies.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\win32\windows.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\testcase_targets.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\exceptions.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\yacc.prf:
..\..\Soft\Qt5.12.0\5.12.0\msvc2017_64\mkspecs\features\lex.prf:
QtNewProject.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile QtNewProject.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-Books-qmake_all sub-Draws-qmake_all sub-MainWidget-qmake_all FORCE

make_first: sub-Books-make_first sub-Draws-make_first sub-MainWidget-make_first  FORCE
all: sub-Books-all sub-Draws-all sub-MainWidget-all  FORCE
clean: sub-Books-clean sub-Draws-clean sub-MainWidget-clean  FORCE
distclean: sub-Books-distclean sub-Draws-distclean sub-MainWidget-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-Books-install_subtargets sub-Draws-install_subtargets sub-MainWidget-install_subtargets FORCE
uninstall_subtargets: sub-Books-uninstall_subtargets sub-Draws-uninstall_subtargets sub-MainWidget-uninstall_subtargets FORCE

sub-Books-debug:
	@if not exist Books\ mkdir Books\ & if not exist Books\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Books\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Books\Books.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-Draws-debug:
	@if not exist Draws\ mkdir Draws\ & if not exist Draws\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Draws\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Draws\Draws.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MainWidget-debug:
	@if not exist MainWidget\ mkdir MainWidget\ & if not exist MainWidget\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MainWidget\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\MainWidget\MainWidget.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-Books-debug sub-Draws-debug sub-MainWidget-debug

sub-Books-release:
	@if not exist Books\ mkdir Books\ & if not exist Books\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Books\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Books\Books.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-Draws-release:
	@if not exist Draws\ mkdir Draws\ & if not exist Draws\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Draws\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Draws\Draws.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MainWidget-release:
	@if not exist MainWidget\ mkdir MainWidget\ & if not exist MainWidget\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MainWidget\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\MainWidget\MainWidget.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-Books-release sub-Draws-release sub-MainWidget-release

sub-Books-check:
	@if not exist Books\ mkdir Books\ & if not exist Books\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Books\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Books\Books.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-Draws-check:
	@if not exist Draws\ mkdir Draws\ & if not exist Draws\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Draws\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Draws\Draws.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MainWidget-check:
	@if not exist MainWidget\ mkdir MainWidget\ & if not exist MainWidget\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MainWidget\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\MainWidget\MainWidget.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-Books-check sub-Draws-check sub-MainWidget-check

sub-Books-benchmark:
	@if not exist Books\ mkdir Books\ & if not exist Books\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Books\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Books\Books.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-Draws-benchmark:
	@if not exist Draws\ mkdir Draws\ & if not exist Draws\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Draws\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\Draws\Draws.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MainWidget-benchmark:
	@if not exist MainWidget\ mkdir MainWidget\ & if not exist MainWidget\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd MainWidget\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\20230808NewQtProject\QtNewProject\MainWidget\MainWidget.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-Books-benchmark sub-Draws-benchmark sub-MainWidget-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

