#ifndef ALLDRAWSDLL_GLOBAL_H
#define ALLDRAWSDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ALLDRAWSDLL_LIBRARY)
#  define ALLDRAWSDLL_EXPORT Q_DECL_EXPORT
#else
#  define ALLDRAWSDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // ALLDRAWSDLL_GLOBAL_H
