#ifndef QT5_9CDEVELOPERGUIDE_GLOBAL_H
#define QT5_9CDEVELOPERGUIDE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QT5_9CDEVELOPERGUIDE_LIBRARY)
#  define QT5_9CDEVELOPERGUIDE_EXPORT Q_DECL_EXPORT
#else
#  define QT5_9CDEVELOPERGUIDE_EXPORT Q_DECL_IMPORT
#endif

#endif // QT5_9CDEVELOPERGUIDE_GLOBAL_H
